### ISSUE TITLE
仕様確認

### ISSUE THREAD

**Issue by yuyatanami** [ing-ent/hotelkyujin-resume-print-form#1]
サーバサイドログイン後、
認可コードから、ユーザ情報をfetchしてフォームに埋め込んで表示。
読み込んでからのそれぞれの値は自由に変更可能。
確認画面へ遷移して、印刷ボタン

**Comment by yuyatanami** [comment]
HTML4なので、 HTML5への修正が必須。

**Comment by yuyatanami** [comment]
入力画面
<img width="934" alt="スクリーンショット 2020-11-18 18 17 38" src="https://user-images.githubusercontent.com/8180046/99510483-7a7bd300-29ca-11eb-9cd4-c0fa9ad28ddd.png">

印刷画面
<img width="893" alt="スクリーンショット 2020-11-18 18 17 45" src="https://user-images.githubusercontent.com/8180046/99510489-7cde2d00-29ca-11eb-995e-658a815d4bcc.png">

@shunashuna 印刷画面に、職歴が入ってるのですが、入力にはありません。これはどうしましょうか

**Comment by shunashuna** [comment]
@yuyatanami これは、今までも職歴の会社名だけを引っ張ってきて表示させてます。

**Comment by yuyatanami** [comment]
@shunashuna なるほどです！会社名(company_name)だけでよいですかね？

**Comment by shunashuna** [comment]
会社名のみで
おっけーです
