### ISSUE TITLE
HTML4なので、 HTML5への修正が必須。

### ISSUE THREAD

**Issue by yuyatanami** [ing-ent/hotelkyujin-resume-print-form#3]
HTML4なので、 HTML5への修正が必須。

_Originally posted by @yuyatanami in https://github.com/ing-ent/hotelkyujin-resume-print-form/issues/1#issuecomment-726428017_

**Comment by yuyatanami** [comment]
@shunashuna 履歴書作成画面のHTML5化、お願いできますでしょうか？

**Comment by shunashuna** [comment]
https://www.hotelkyujin.com/hotel-resume
ここです？？

**Comment by yuyatanami** [comment]
@shunashuna はい、そうです！
